<option value="mitsubishi">Mitsubishi</option>
<option value="volvo">Volvo</option>
<option value="kia">Kia</option>
<option value="jeep">Jeep</option>
<option value="volkswagen">Volkswagen</option>
<option value="hyundai">Hyundai</option>
<option value="nissan">Nissan</option>
<option value="mercedes-benz">Mercedes-Benz</option>
<option value="toyota">Toyota</option>
<option value="opel">Opel</option>
<option value="ford">Ford</option>
<option value="mazda">Mazda</option>
<option value="smart">Smart</option>
<option value="bmw">BMW</option>
<option value="lada-vaz">LADA (ВАЗ)</option>
<option value="skoda">Skoda</option>
<option value="jaguar">Jaguar</option>
<option value="suzuki">Suzuki</option>
