<option value="lada-vaz">LADA (ВАЗ)</option>
<option value="kia">Kia</option>
<option value="jeep">Jeep</option>
<option value="nissan">Nissan</option>
<option value="suzuki">Suzuki</option>
<option value="chevrolet">Chevrolet</option>
<option value="hyundai">Hyundai</option>
<option value="citroen">Citroen</option>
<option value="lada-vaz">Lada (ВАЗ)</option>
<option value="renault">Renault</option>
<option value="lexus">Lexus</option>
<option value="mitsubishi">Mitsubishi</option>
<option value="volkswagen">Volkswagen</option>
<option value="ford">Ford</option>
<option value="ssangyong">SsangYong</option>
<option value="skoda">Skoda</option>
<option value="lifan">Lifan</option>
<option value="toyota">Toyota</option>
<option value="daewoo">Daewoo</option>
<option value="volvo">Volvo</option>
<option value="land-rover">Land Rover</option>
<option value="bmw">BMW</option>
<option value="opel">Opel</option>
<option value="mercedes-benz">Mercedes-Benz</option>
